image:
  - Visual Studio 2017

clone_depth: 1
shallow_clone: false

# All paths in the environment section should be
# cmake-style paths: using forward-slashes (/).
environment:
  PYTHON: "C:\\Python36-x64"
  CMAKE_GENERATOR: "Visual Studio 15 2017"
  BOOST_ROOT: "C:\\Libraries"
  BOOST_VERSION: "1.65.1"
  DEP_DIR: "C:\\dependencies"
  WIN_DEP_NAME: "openrw-windows-dependencies"
  WIN_DEP_URL: "https://github.com/rwengine/openrw-windows-dependencies"
  NAME_SUFFIX: "windows"

platform:
  - Win32
#  - x64

configuration:
#  - Debug
  - Release

matrix:
  fast_finish: false

cache:
  - C:\dependencies -> .appveyor.yml, cmake/ctest/script_ci.ctest, cmake/ctest/utils.ctest, , cmake/ctest/configure_windows.ctest

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - cmake --version
  - msbuild /version

build_script:
  - ctest -VV -S cmake/ctest/script_ci.ctest
  - cmake --build  "%APPVEYOR_BUILD_FOLDER%\build\rwgame" --target install --config Release

# scripts to run after build
after_build:
  - 7z a openrw-%appveyor_repo_branch%.zip %APPVEYOR_BUILD_FOLDER%\build\bin\*

artifacts:
  - path: openrw-$(appveyor_repo_branch).zip

deploy:
  - provider: Environment
    name: openrw-master
    release: openrw-$(appveyor_repo_branch)-v$(appveyor_build_version)
    artifact: openrw-$(appveyor_repo_branch).zip
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      configuration: release        # deploy release builds only
      appveyor_repo_tag: true       # deploy on tag push only
      is_not_pr: true               # don't deploy pull requests

