sudo: required
dist: trusty
language: generic
env:
  - CXX=g++-5 CC=gcc-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libbullet-dev
      - libsdl2-dev
      - libglm-dev
      - libopenal-dev
      - libavcodec-dev
      - libavformat-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      # Dependencies for BUILD_TESTS
      - libboost-test-dev
      # Dependencies for BUILD_VIEWER
      - qt5-default
      - libqt5opengl5-dev
git:
    depth: 3
script:
    - ctest -S cmake/ctest/travis_script.ctest -VV -DSRC_DIR=. -DBIN_DIR=build
    - if [ -f FATAL_ERROR ]; then printf "Fatal failure detected.\nExiting with non-zero result code.\n"; exit 1; fi
notifications:
    email: false
#    irc:
#        channels:
#            - chat.freenode.net#openrw
#        template:
#            - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
