language: cpp

git:
    depth: 3

matrix:
  include:
  - os: linux
    env: NAME="Ubuntu Linux (Latest)" NAME_SUFFIX="ubuntu"
    services: docker
    script:
      - scripts/docker/docker_travis.sh "ubuntu_latest.docker"
  - os: linux
    env: NAME="Fedora Linux (Latest)" NAME_SUFFIX="fedora"
    services: docker
    script:
      - scripts/docker/docker_travis.sh "fedora_latest.docker"
  - os: linux
    env: NAME="Arch Linux (Latest)" NAME_SUFFIX="arch"
    services: docker
    script:
      - scripts/docker/docker_travis.sh "arch_latest.docker"
  - os: osx
    env: NAME="Apple macOS" NAME_SUFFIX="mac"
    osx_image: xcode9.2
    install:
      - brew update
      - brew upgrade python
      - brew upgrade
      - brew install boost cmake bullet ffmpeg glm openal-soft qt5 sdl2 jack
      - export PATH="/usr/local/opt/qt/bin:$PATH"
    script:
      - mkdir -p "$TRAVIS_BUILD_DIR/build"
      - ctest -VV -S "$TRAVIS_BUILD_DIR/cmake/ctest/script_ci.ctest"

notifications:
    email: false
#    irc:
#        channels:
#            - chat.freenode.net#openrw
#        template:
#            - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
