sudo: required
dist: trusty
language: generic
env:
  - CXX=g++-5 CC=gcc-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libbullet-dev
      - libsdl2-dev
      - libglm-dev
      - libopenal-dev
      - libavcodec-dev
      - libavformat-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      # Dependencies for BUILD_TESTS
      - libboost-test-dev
      # Dependencies for BUILD_VIEWER
      - qt5-default
      - libqt5opengl5-dev
git:
    depth: 3
script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TESTS=1 -DTESTS_NODATA=1 -DBUILD_VIEWER=1 && make
    - tests/run_tests
notifications:
    email: false
#    irc:
#        channels:
#            - chat.freenode.net#openrw
#        template:
#            - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
